### PR TITLE
Fix resource renaming

### PR DESCRIPTION
**Pull request by mobile46**
Fix resource renaming for ConfuserEx

de4dot

### CODE REVIEW

**Comment by scouteh** [comment]
There is no need, it literally shows the names.

**Comment by mobile46** [comment]
Nope, it's not working properly because of the backslashes in the resource names. You can try it out.

**Comment by scouteh** [comment]
I mean if you want to know the full names you can use your brain

**Comment by mobile46** [comment]
Well, you don't know what you say. Now use your brain and understand the difference!

brain-checker

**Comment by 0xd4d** [comment]
I think this can be fixed by just updating `ResourceRenamer`.

Types that are used as resource names are escaped. `, [ ] & * + \` must be escaped, eg. `,` => `\,`.

All names that the code reads from a `TypeInfo` should be escaped.

```C#
		static bool IsReservedTypeNameChar(char c) {
			switch (c) {
			case ',':
			case '[':
			case ']':
			case '&':
			case '*':
			case '+':
			case '\\':
				return true;
			default:
				return false;
			}
		}

		static bool HasReservedTypeNameChar(string s) {
			foreach (var c in s) {
				if (IsReservedTypeNameChar(c))
					return true;
			}
			return false;
		}

		static string EscapeTypeName(string name) {
			if (!HasReservedTypeNameChar(name))
				return name;
			var sb = new StringBuilder();
			foreach (var c in name) {
				if (IsReservedTypeNameChar(c))
					sb.Append('\\');
				sb.Append(c);
			}
			return sb.ToString();
		}
```

**Comment by CreateAndInject** [comment]
@0xd4d This PR can't resolve this bug completely, I'll send a PR later.

**Comment by 0xd4d** [comment]
@CreateAndInject Just explain what is wrong and he'll fix it, that's what PR comments are for. ;)

**Comment by CreateAndInject** [comment]
@0xd4d For example
Type `abc' ask for `abc.resources`
Type `ab\c` ask for `ab\\c.resources`
In this PR, both 2 types ask for `abc.resources`

I meet this issue a few years ago, my code work fine these years, I have sended a PR.

**Comment by 0xd4d** [comment]
> @0xd4d For example
> Type `abc` ask for `abc.resources`
> Type `ab\c` ask for `ab\\c.resources`
> In this PR, both 2 types ask for `abc.resources`

It will be fixed in this PR, I already mentioned that they must be escaped, see https://github.com/0xd4d/de4dot/pull/204#issuecomment-595847576

**Comment by mobile46** [comment]
Thank you @0xd4d @CreateAndInject. Is it okay now?

**Comment by 0xd4d** [comment]
I think these are the only locations that must be escaped:

- https://github.com/0xd4d/de4dot/blob/master/de4dot.code/renamer/ResourceRenamer.cs#L80
- https://github.com/0xd4d/de4dot/blob/master/de4dot.code/renamer/ResourceRenamer.cs#L146
- https://github.com/0xd4d/de4dot/blob/master/de4dot.code/renamer/ResourceRenamer.cs#L151

**Comment by CreateAndInject** [comment]
@0xd4d I don't think so:
These 2 must be escaped
https://github.com/0xd4d/de4dot/blob/master/de4dot.code/renamer/ResourceRenamer.cs#L61
https://github.com/0xd4d/de4dot/blob/master/de4dot.code/renamer/ResourceRenamer.cs#L146

It's better to escape these 2, because the new name is cleaned can't shouldn't contains these character:
https://github.com/0xd4d/de4dot/blob/master/de4dot.code/renamer/ResourceRenamer.cs#L80
https://github.com/0xd4d/de4dot/blob/master/de4dot.code/renamer/ResourceRenamer.cs#L151

By the way, I think it's no need to add `EscapeTypeName`, ReflectionFullName do the same thing, if .Net add more ReservedTypeNameChar in the future, we're unnecessary to modify these code, since new dnlib will do it.

**Comment by 0xd4d** [comment]
I'll add line 61 in a new commit. The other lines you mentioned have already been fixed by @mobile46

**Pull request merged**
