### PR TITLE
Phoenix Protector and Orange Heap support (done by: TheProxy)

### PR DESCRIPTION
**Pull request by mrexodia**
join the discussion [here](https://forum.tuts4you.com/topic/37122-de4dot-cryptophoenixreactororangeheap-fixed-by-ivancitooz)

### CODE REVIEW

**Comment by 0xd4d** [comment]
I don't accept new deobfuscators unless it's for something that's widely used. There's probably hundreds of .NET obfuscators already, and de4dot shouldn't support anything that exists. AFAIK, those two obfuscators are barely used by anyone. Is that correct?

**Comment by mrexodia** [comment]
Why not? It's just a simple addition no structural code changes or anything. Doesn't hurt to support a few more obfuscators. Phoenix I encountered various times in the field, never heard of the Orange Heap one, but doesn't hurt to support that either.

**Comment by 0xd4d** [comment]
The more deobfuscators that are added, the more work I have to do. Because it will be I who will have to update the code later. That's why I stopped adding new deobfuscators a long time ago even though writing one is trivial.

**Comment by 0xd4d** [comment]
BTW, it's better to spend the time updating the support for the already supported obfuscators. Unfortunately I don't have enough time at the moment.

**Comment by mrexodia** [comment]
Okay :) It would be possible to add dynamically loaded deobfuscation modules right? Would you accept a pull for that? I don't want to waste my time that much.

Dynamic modules would solve your maintenance problems.

**Comment by 0xd4d** [comment]
Yes, I would.

**Comment by mrexodia** [comment]
Awesome! I'll try doing that tonight.

**Pull request closed without merging**
