### PR TITLE
Agile VM Support

### PR DESCRIPTION
**Pull request by cawk**
This supports the latest VM for agile
version number 6.4.0.23

the only opcode that i havent added is Ldvirtftn this is due to whenever protecting a file with this opcode agile obfuscator crashed

i removed 
if (handlers.Count < NUM_HANDLERS)
					continue;

due to not all handlers get added to the assembly
i take it they were before in older versions?

### CODE REVIEW

**Comment by 0xd4d** [comment]
This VM doesn't seem to offer much protection, is it still being actively developed?

> the only opcode that i havent added is Ldvirtftn this is due to whenever protecting a file with this opcode agile obfuscator crashed

Report the bug. :laughing:

Are you sure there was no problem with your code? (If the IL was generated by the C#/VB compiler, then the code is most likely bug free).

> i removed
> if (handlers.Count < NUM_HANDLERS)
> continue;
> 
> due to not all handlers get added to the assembly
> i take it they were before in older versions?

How many handlers exist now? Maybe the constant should be updated.

**Comment by cawk** [comment]
> This VM doesn't seem to offer much protection, is it still being actively developed?

Im not too sure on this, i know i see a few requests for its unpacking 
but that wasnt the point of this update i just wanted to test myself with a different VM 

> Report the bug. 😆

i will do soon, just making sure theres no fault on my side first 

> How many handlers exist now? Maybe the constant should be updated. 

this changes per obfuscation

my guess is that they used to inject all handlers in the applications before (i dont have a test file of an older version to confirm this)
and now they seem to inject the handlers they need

**Comment by 0xd4d** [comment]
> i will do soon, just making sure theres no fault on my side first

Here's some code that will use ldvirtftn in case you only used IL before:

```C#
class C {
	public virtual void M() { }
}

var c = new C();
Action action = c.M;
```

**Comment by cawk** [comment]
Thanks! that worked 
my understanding of that instruction was wrong!

ive added support for that opcode now 

http://www73.zippyshare.com/v/6cvHejgk/file.html

theres a download for a file with those opcodes in as a test file incase you wanted to make some tests

**Comment by 0xd4d** [comment]
Thanks!

**Pull request merged**
