### PR TITLE
Dynamic deobfuscation modules

### PR DESCRIPTION
**Pull request by mrexodia**
This pull requests makes every deobfuscation module load dynamically. The deobfuscation modules from `de4dot.code` are all moved to separate projects named `deobfuscator.*.dll`. I believe this makes everything more organized.

All interfaces/classes in `de4dot.code` were made public, so users can use all features the original `de4dot.code.deobfuscators` used.

I also added a template so users can make their own modules very easily. I tried to separate different modification stages so everything should be clear. Some formatting might have gotten off, since my VS likes doing things when you save a file.

### CODE REVIEW

**Comment by 0xd4d** [comment]
> This pull requests makes every deobfuscation module load dynamically. The deobfuscation modules from de4dot.code are all moved to separate projects named deobfuscator.*.dll. I believe this makes everything more organized.

They were already organized, one directory per deobfuscator. ;) I don't like having one extra small assembly per deobfuscator when they're already part of de4dot. The original deobfuscators should remain where they are.

Lots of files have had their formatting changed from the de4dot coding style to your coding style (spaces instead of tabs, braces on next line etc). Sure VS does stuff when you paste, but you can always undo that by either pressing Ctrl+Z or by editing the VS options that it shouldn't reformat when pasting. That setting can be restored again when you're done.

I had expected code to scan a directory, perhaps the de4dot bin dir or something for plugins and load them, and making some required classes/ifaces public when necessary.

**Comment by mrexodia** [comment]
There is no static code for deobfuscator module loading anymore. The separation makes the 'original deobfuscators' plugins and loads those dynamically instead. You can find that code [over here](https://github.com/mrexodia/de4dot/blob/9b2d57a7ab0008c2ae87a8d14c3595917fb2f068/de4dot.cui/Program.cs#L40)

Separated deobfuscator files also allow for easier customization/upgrading of the current deobfuscators. Upgrading becomes just updating that specific deobfuscator library instead of the whole `de4dot.code` library.

Fixed all the formatting things.

**Comment by berryman13** [comment]
Mr. Exodia, seeing your fork of de4dot on my github control panel made me absolutely giddy +1
I love seeing your work man, it's just so....great! x64dbg is quickly becoming one of my favorite debuggers. 

I'm super excited to see what else you will bring to the table man!

**Comment by 0xd4d** [comment]
You haven't pushed anything over here yet.

There's no way I'm going to include a pull request that splits up a dll file into 20 other DLL files. Just because you can doesn't mean you should. Pretty much any DLL file you'll find could be split up into smaller units. So why don't people do it? How many DLL files could mscorlib be split up into? Could be a nice weekend project. :)

Dynamically finding the deobfuscators is something I chose not to do for the simple reason that it's known at compile time which deobfuscator is present or not. That's OK with plugins, though.

Your commits now are mostly fixes of older commits, and one commit even includes a binary file! It needs to be cleaned up and fixed. `git reset master` and then `git add .` and finally check the diff before committing it.

**Pull request closed without merging**
