### PR TITLE
Dynamic loading fix

### PR DESCRIPTION
**Pull request by mrexodia**
Made all interfaces/classes in `de4dot.code` public.

Added dynamic loading of deobufscator modules in `bin\deobfuscator.*.dll`.

Added a template for a deobfuscator module (not included in main solution).

### CODE REVIEW

**Comment by mrexodia** [comment]
hm, i still don't like that there are deobfuscator modules built-in... wouldn't there be a way to automatically disable the built-in modules when a dll version is found?

I looked at using `DeobfuscatorInfoBase.THE_TYPE` to do this, but there could be multiple deobfuscators for one type...

**Comment by 0xd4d** [comment]
There should only be one deobfuscator with the same type name. You could disable them where you create them. If a loaded DLL already uses that type, don't add the default one.

**Comment by mrexodia** [comment]
Okay, missed that one (thought .NET Reactor had the same type name). I'll implement this soon (exams coming up :+1:)

**Comment by 0xd4d** [comment]
OK, push it here when done and I'll merge the pull request.

Good luck. :)

**Comment by mrexodia** [comment]
Hey,

Finished my last exam today and pushed the final commit. I just used a dictionary so there cannot be multiple plugins with the same type name and it is also possible to overload the default deobfuscators.

**Pull request merged**
