### PR TITLE
Support .NETReactor last versions.

### PR DESCRIPTION
**Pull request by XODE0**
Tested also on v4.9.7.0 and the last version(v5.0.0.0), I used this pull request [https://github.com/0xd4d/de4dot/pull/118](https://github.com/0xd4d/de4dot/pull/118) to support v4.9.7.0.

### CODE REVIEW

**Comment by 0xd4d** [comment]
This breaks eg. DNR 4.0 files, similar to #118

**Comment by XODE0** [comment]
I believe this should fix the issue (tested on 4, 4.1, 4.9.7, 4.9.9, 5).

**Comment by 0xd4d** [comment]
Almost done. It fails DNR 4.7.

**Comment by 0xd4d** [comment]
BTW, have you tested it on the file released yesterday?

**Comment by XODE0** [comment]
ok i will check the version 4.7

> BTW, have you tested it on the file released yesterday?



what file ?

**Comment by 0xd4d** [comment]
DNR 5.0, timestamp March 18

**Comment by XODE0** [comment]
I tested it on the version V5.0.0.0 that released in 8-Mar-2016
can you send to me that version ?

**Comment by 0xd4d** [comment]
Just use the normal download link from their site.

**Comment by XODE0** [comment]
Yes ,i downloaded the version that i tested it from their site today, so it is fine.

**Comment by XODE0** [comment]
ok this should fix it , tested on 4.7, 4.8, 4.9 and 

> (tested on 4, 4.1, 4.9.7, 4.9.9, 5).

**Comment by 0xd4d** [comment]
Thanks, worked like a charm.

**Comment by cawk** [comment]
Doesnt actually work for 5.0 if you need the test file let me know

**Comment by XODE0** [comment]
ok, can you post it ?

**Comment by cawk** [comment]
using this one it does work 
https://github.com/0xd4d/de4dot/pull/120/commits/f6a107c9bf41fca2a4c2c829181705a4d0a52161
but using the one 0xd4d forked in it doesnt 
so just might be an error with the one he actually forked

**Comment by XODE0** [comment]
can you share the file so i can find the problem ?
because i tested it many times with the last version and it does work 
try to use this 
[https://ci.appveyor.com/project/0xd4d/de4dot/build/artifacts](https://ci.appveyor.com/project/0xd4d/de4dot/build/artifacts)

**Comment by cawk** [comment]
it breaks support for net reactor 4.4

**Comment by Alex-Yuen** [comment]
I tested the latest version, it does not work, dotNETReactor v5.0.0.0

**Comment by Alex-Yuen** [comment]
I know, has been fixed

**Comment by claudedbKind** [comment]
I tested the latest version, it does not work, dotNETReactor v5.0.0.0 when select "NecroBit" or "String Encryption" option.
how to fix?

**Comment by claudedbKind** [comment]
> I know, has been fixed,Version checking is incorrect

how to fix? @Alex-Yuen

**Comment by rolandh** [comment]
Download the source code, load up visual studio and extend the routines

**Pull request merged**
