### PR TITLE
supporting generic string decrypter methods

### PR DESCRIPTION
**Pull request by spresec**
I do not believe de4dot currently supports decrypting strings where the string decrypter method is a generic method.

For example, when looking at the flare-on challenge #9, GUI.exe, it is obfuscated using ConfuserEx v1.0.0 (download from http://flare-on.com/files/Flare-On3_Challenges.zip, password: "flare").

After using de4dot to clean up symbols, we see the calls to several string decrypter methods:
gui_exe_button1_click_obfuscated_strings

As you can see, these string decrypter methods are generic methods. Currently, de4dot expects string decrypter methods to return the type "string" or "object", but doesn't currently handle generic methods like this (unless I'm missing something :) ). 

The changes in this pull request update the delegate type string decrypter to decrypt strings from generic methods.

After applying these changes, and running de4dot.exe the strings are successfully decrypted.

```
C:\>de4dot.exe -f GUI.exe -o GUI1.exe

de4dot v3.1.41592.3405 Copyright (C) 2011-2015 de4dot@gmail.com
Latest version and source code: https://github.com/0xd4d/de4dot

Detected Unknown Obfuscator (C:\GUI.exe)
Cleaning C:\GUI.exe
Renaming all obfuscated symbols
Saving C:\GUI1.exe

C:\>de4dot.exe -f GUI1.exe --strtyp delegate --strtok 06000004 --strtyp delegate --strtok 06000005 --strtyp delegate --strtok 06000006 --strtyp delegate --strtok 06000007 --strtyp delegate --strtok 06000008 -o GUI2.exe

de4dot v3.1.41592.3405 Copyright (C) 2011-2015 de4dot@gmail.com
Latest version and source code: https://github.com/0xd4d/de4dot

Detected Unknown Obfuscator (C:\GUI1.exe)
Cleaning C:\GUI1.exe
Renaming all obfuscated symbols
Saving C:\GUI2.exe
```

The strings are now successfully decrypted:
de4dot_strings_decrypted

This may not be the best way to add support for generic methods, please advise if you'd like this to be updated using a different approach. Thanks!

### CODE REVIEW

**Comment by 0xd4d** [comment]
This only works with methods that take one string argument, it won't work with eg. `V Method<T, U, V>(T t, U u)`.

**Comment by 0xd4d** [comment]
Instead of hard coding the `string` generic argument, you should pass in the actual generic arguments when creating the generic method info.

**Comment by spresec** [comment]
Great, thanks for the response. I'll update this PR when I get a chance with your suggested approach.

**Comment by mems** [comment]
I don't know if it's related, but if I try this example with the last version (v3.1.41592.3405), I've got the following error:
```
ERROR:   Method return type must be string or object: T smethod_2[T](UInt32)
```

It's look like the generics are not/no more supported

**Pull request closed without merging**
